// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUFGB2XQSEKstI5eSZKdtnVAkOoan5oHo',
    appId: '1:884575119093:web:e4d632afe2ae8a4cd047bc',
    messagingSenderId: '884575119093',
    projectId: 'bb-call',
    authDomain: 'bb-call.firebaseapp.com',
    storageBucket: 'bb-call.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesZ3250S-HQqwugPBU25Tv3JVbpT-LNI',
    appId: '1:884575119093:android:534ceca8ae920834d047bc',
    messagingSenderId: '884575119093',
    projectId: 'bb-call',
    storageBucket: 'bb-call.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLsqt2oiCqldJhBtH8Mx_itoY0yPNGjfI',
    appId: '1:884575119093:ios:74c81bd8ab3eac2ed047bc',
    messagingSenderId: '884575119093',
    projectId: 'bb-call',
    storageBucket: 'bb-call.firebasestorage.app',
    iosBundleId: 'com.example.bbcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLsqt2oiCqldJhBtH8Mx_itoY0yPNGjfI',
    appId: '1:884575119093:ios:74c81bd8ab3eac2ed047bc',
    messagingSenderId: '884575119093',
    projectId: 'bb-call',
    storageBucket: 'bb-call.firebasestorage.app',
    iosBundleId: 'com.example.bbcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUFGB2XQSEKstI5eSZKdtnVAkOoan5oHo',
    appId: '1:884575119093:web:00948e345c744839d047bc',
    messagingSenderId: '884575119093',
    projectId: 'bb-call',
    authDomain: 'bb-call.firebaseapp.com',
    storageBucket: 'bb-call.firebasestorage.app',
  );
}
