// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uALMa51qacNF45p2KEGluHn0fdUj0oE',
    appId: '1:1063589342716:web:0ad5d5c4b5a287aacd5679',
    messagingSenderId: '1063589342716',
    projectId: 'smart-nfu',
    authDomain: 'smart-nfu.firebaseapp.com',
    storageBucket: 'smart-nfu.firebasestorage.app',
    measurementId: 'G-KL4K6H45HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMWb-CBp0i-CGGJEhAqBBdxUfILBbQQc',
    appId: '1:1063589342716:android:2f04def114a22304cd5679',
    messagingSenderId: '1063589342716',
    projectId: 'smart-nfu',
    storageBucket: 'smart-nfu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrpja2b4fKXQwA-nvEN79jnOcYcDLIXQ',
    appId: '1:1063589342716:ios:1d9fa2f5fde130d1cd5679',
    messagingSenderId: '1063589342716',
    projectId: 'smart-nfu',
    storageBucket: 'smart-nfu.firebasestorage.app',
    iosBundleId: 'com.example.nfu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrpja2b4fKXQwA-nvEN79jnOcYcDLIXQ',
    appId: '1:1063589342716:ios:1d9fa2f5fde130d1cd5679',
    messagingSenderId: '1063589342716',
    projectId: 'smart-nfu',
    storageBucket: 'smart-nfu.firebasestorage.app',
    iosBundleId: 'com.example.nfu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2uALMa51qacNF45p2KEGluHn0fdUj0oE',
    appId: '1:1063589342716:web:bfb0df26d30adab4cd5679',
    messagingSenderId: '1063589342716',
    projectId: 'smart-nfu',
    authDomain: 'smart-nfu.firebaseapp.com',
    storageBucket: 'smart-nfu.firebasestorage.app',
    measurementId: 'G-Y1YDS1Y52J',
  );
}
